# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Get the certificates and provisioning profiles"
  lane :certificates do
    match(type: "development", readonly: true)
    match(type: "appstore", readonly: true)
  end

  desc "Build the app"
  lane :build do
  	certificates
  	build_app(scheme: "Bicisendas")
  end

  desc "Run the unit tests"
  lane :tests do
    run_tests(scheme: "Bicisendas")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
  	build
    upload_to_testflight
  end
end
